Output demo.gif

Require ./mkill

Set Margin 20
Set MarginFill "#674EFF"
Set BorderRadius 10
Set Width 1200
Set Height 800
Set TypingSpeed 200ms
Set Theme "Catppuccin Mocha"

Type "./mkill"
Sleep 1s
Enter

Sleep 6s

Type "?"
Sleep 6s

Type "escape"
Sleep 2s

# Show protection
Down
Sleep 1s
Down
Sleep 1s
Type "p"
Sleep 2s
Type "p"
Sleep 2s

# Show manual kill
Type "k"
Sleep 2s
Type "escape"
Sleep 2s

# Show saving
Type "P"
Sleep 2s

Type "-"
Sleep 1s
Type "-"
Sleep 1s
Type "="
Sleep 2s

Type "q"
Sleep 2s
